import mongoose from "mongoose";
import dotenv from "dotenv";
import Vehicle from "./models/vehicle.js";

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const vehicles = [
    {
        name: "Ferrari Roma",
        price: "₹3.76 Cr",
        category: "Coupe",
        image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8",
        tag: "Luxury",
        year: "2023",
        fuel: "Petrol",
        power: "612 HP",
        topSpeed: "320 km/h",
        zeroToSixty: "3.4s",
        transmission: "Automatic",
        drivetrain: "RWD",
        seats: "2",
        color: "Rosso Red",
        mileage: "5,000 km",
        description: "Elegant Italian coupe with extreme performance",
    },
    {
        name: "Lamborghini Huracán EVO",
        price: "₹4.99 Cr",
        category: "Coupe",
        image: "https://images.unsplash.com/photo-1621135802920-133df287f89c",
        tag: "Supercar",
        year: "2023",
        fuel: "Petrol",
        power: "631 HP",
        topSpeed: "325 km/h",
        zeroToSixty: "2.9s",
        transmission: "Automatic",
        drivetrain: "AWD",
        seats: "2",
        color: "Yellow",
        mileage: "3,000 km",
        description: "Track-focused V10 beast",
    },
    {
        name: "Maruti Jimny",
        price: "₹15 L",
        category: "SUV",
        image: "https://images.unsplash.com/photo-1682687982501-1e58ab814714",
        tag: "Popular",
        year: "2024",
        fuel: "Petrol",
        power: "103 HP",
        topSpeed: "145 km/h",
        zeroToSixty: "12s",
        transmission: "Manual",
        drivetrain: "4x4",
        seats: "4",
        color: "Green",
        mileage: "8,000 km",
        description: "Compact off-road SUV",
    },
    {
        name: "Tata Nexon EV Max",
        price: "₹19 L",
        category: "SUV",
        image: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2",
        tag: "EV",
        year: "2024",
        fuel: "Electric",
        power: "143 HP",
        topSpeed: "140 km/h",
        zeroToSixty: "9s",
        transmission: "Automatic",
        drivetrain: "FWD",
        seats: "5",
        color: "Blue",
        mileage: "12,000 km",
        description: "India’s top EV SUV",
    },
    {
        name: "Toyota Fortuner",
        price: "₹35 L",
        category: "SUV",
        image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
        tag: "Best Seller",
        year: "2023",
        fuel: "Diesel",
        power: "201 HP",
        topSpeed: "190 km/h",
        zeroToSixty: "10s",
        transmission: "Automatic",
        drivetrain: "4x4",
        seats: "7",
        color: "White",
        mileage: "20,000 km",
        description: "Powerful and reliable SUV",
    },
    {
        name: "Ford Mustang GT",
        price: "₹75 L",
        category: "Coupe",
        image: "https://images.unsplash.com/photo-1584345604327-7a1b0cdb9a1f",
        tag: "Muscle",
        year: "2023",
        fuel: "Petrol",
        power: "450 HP",
        topSpeed: "250 km/h",
        zeroToSixty: "4.2s",
        transmission: "Manual",
        drivetrain: "RWD",
        seats: "4",
        color: "Black",
        mileage: "6,000 km",
        description: "Classic American muscle car",
    },
    {
        name: "Hyundai IONIQ 6",
        price: "₹60 L",
        category: "Sedan",
        image: "https://images.unsplash.com/photo-1674821444793-0c54b8e1b6c6",
        tag: "Electric",
        year: "2024",
        fuel: "Electric",
        power: "320 HP",
        topSpeed: "185 km/h",
        zeroToSixty: "5.1s",
        transmission: "Automatic",
        drivetrain: "AWD",
        seats: "5",
        color: "Silver",
        mileage: "2,000 km",
        description: "Futuristic electric sedan",
    },
    {
        name: "Honda City",
        price: "₹12 L",
        category: "Sedan",
        image: "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b",
        tag: "Reliable",
        year: "2022",
        fuel: "Petrol",
        power: "121 HP",
        topSpeed: "180 km/h",
        zeroToSixty: "10s",
        transmission: "Manual",
        drivetrain: "FWD",
        seats: "5",
        color: "Grey",
        mileage: "25,000 km",
        description: "Reliable daily sedan",
    },
    {
        name: "Kawasaki Ninja ZX-6R",
        price: "₹11 L",
        category: "Bike",
        image: "https://images.unsplash.com/photo-1609630875171-b1321377ee65",
        tag: "Sport",
        year: "2023",
        fuel: "Petrol",
        power: "127 HP",
        topSpeed: "260 km/h",
        zeroToSixty: "3.2s",
        transmission: "Manual",
        drivetrain: "Chain",
        seats: "2",
        color: "Green",
        mileage: "4,000 km",
        description: "High-performance sport bike",
    },
];

const seedDB = async () => {
    await Vehicle.deleteMany();
    await Vehicle.insertMany(vehicles);
    console.log("Data Seeded 🔥");
    process.exit();
};

seedDB();